### PR TITLE
cabal: bump quickcheck version

### PR DESCRIPTION
**Pull request by cheecheeo**

### CODE REVIEW

**Comment by bergmark** [comment]
@cheecheeo any chance of getting this released? The test suite is disabled on stackage at the moment. Thanks!

**Comment by cheecheeo** [comment]
@bergmark I'll shoot for getting a release out tonight.

**Comment by cheecheeo** [comment]
@bergmark released: http://hackage.haskell.org/package/cgi-3001.3.0.2/src/cgi.cabal

**Comment by bergmark** [comment]
Thanks!

**Pull request merged**
